### ISSUE TITLE
Unable to run turtlesim inside the container

### ISSUE THREAD

**Issue by uree** [JanezCim/ros2workshop#1]
on Ubuntu 18.04

`ros2 run turtlesim turtlesim_node`

Error message (with `QT_DEBUG_PLUGINS=1`)
```
Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/opt/ros/humble/lib/turtlesim/platforms" ...
loaded library "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so"
No protocol specified
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

[ros2run]: Aborted
```

**Comment by uree** [comment]
I have tried a number of things. In the end the solution was to run  `xhost +local:docker` on the host machine and restart the docker container. This gives docker the permission to connect to the X server running on host ie. there was nothing wrong with xcb or qt just with the way docker accesses the display(s).

**Comment by JanezCim** [comment]
Yeah, docker accessing the displays is always a pain to figure out for different versions of linux. So I guess you figured out the solution, I can simply add the instruction to run `xhost +local:docker` to README for future reference and mark this as solved?

**Comment by JanezCim** [comment]
I've added your solution to the README and i consider this as done, reopen if needed
